# brownie default values made explicit
compiler:
    evm_version: null
    solc:
        version: 0.8.2
        optimizer:
            enabled: true
            runs: 200
        # https://eth-brownie.readthedocs.io/en/stable/compile.html#compiler-settings
        remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"
        - "@gif-interface=etherisc/gif-interface@1.5.0-staging-j"
    vyper:
        version: null

networks:
    default: gifganache
    

# packages below will be added to brownie
# you may use 'brownie pm list' after 'brownie compile' 
# to list the packages installed via the dependency list below
dependencies:
    # github dependency format: <owner>/<repository>@<release>
    - OpenZeppelin/openzeppelin-contracts@4.7.0
    - etherisc/gif-interface@1.5.0-staging-j

# exclude Ownable when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
# reports:
#   exclude_contracts:
#     - Ownable
