= Fire insurance product

:toc:

== Introduction

This section explains how to compile, deploy and interact with the fire insurance example product.

The fire insurance product is a simple example product that can be used to demonstrate the basic functionality of the GIF platform. 
It is a simple parametric insurance product that pays out an amount of USDC if a fire event is triggered by the oracle depending on the fire category (_S_ - no payout, _M_ - 20% of the sum insured, _L_ - 100% of the sum insured).

== Compiling and running the unit tests

Start with compiling all contracts.

[source,bash]
----
brownie compile --all
----

Before running the tests for the first time you will likely need to add an empty `.env` file before.

[source,bash]
----
touch /home/vscode/.brownie/packages/etherisc/gif-contracts@b58fd27/.env
----

Now run the unit tests for the sandbox.
[source,bash]
----
brownie test -n auto
----

This shoud result in output similar to the one provided below.

[source,bash]
----
⬢ [Docker] ❯ brownie test -n auto
Brownie v1.19.3 - Python development framework for Ethereum

================================================================= test session starts =================================================================
platform linux -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /workspace
plugins: eth-brownie-1.19.3, forked-1.4.0, hypothesis-6.27.3, web3-5.31.3, xdist-1.34.0, anyio-3.6.2
gw0 [8] / gw1 [8] / gw2 [8] / gw3 [8] / gw4 [8] / gw5 [8] / gw6 [8] / gw7 [8]
........                                                                                                                                        [100%]
-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================== 8 passed, 101 warnings in 44.52s ===========================================================
----

The important part is that all tests pass and no errors or failures are shown.

== Deploy and Verify with Ganache

[source,bash]
----
brownie console
----

In the console use the following steps.

[source,python]
----
from scripts.deploy_fire import help
help()
----

The help command then shows an example session.

[source,python]
----
from scripts.deploy_fire import all_in_1, verify_deploy, create_bundle, create_policy, help

(customer, customer2, product, oracle, riskpool, riskpoolWallet, investor, usdc, instance, instanceService, instanceOperator, bundleId, processId, d) = all_in_1(deploy_all=True)

verify_deploy(d, usdc, product)
----

This will deploy a new GIF instance as well as the fire insurance product and verify the installation. 

== Deploy to a different network containing a pre-installed GIF instance

As an example use the Ganache chain that runs in a separate container (`ganache`) of this devcontainer setup.

[source,bash]
----
brownie console --network=ganache
----

With an existing instance set parameter `deploy_all=False`.
In this case the file `gif_instance_address.txt` needs to exist and contain the addresses of the instance registry
The file should be automatically created during the devconainer setup procedure of this repository.

[source,python]
----
from scripts.deploy_fire import all_in_1, verify_deploy, create_bundle, create_policy, help

(customer, customer2, product, oracle, riskpool, riskpoolWallet, investor, usdc, instance, instanceService, instanceOperator, bundleId, processId, d) = all_in_1(deploy_all=False)

verify_deploy(d, usdc, product)
----

== Interacting with the fire insurance product

=== Creating a new policy

[source,python]
----
from scripts.util import s2h

# fund customer wallet and approve treasry with a large amount for simplicity
usdc.transfer(customer, 100000 * 10 ** 6, {'from': instanceOperator})
usdc.approve(instanceService.getTreasuryAddress(), 100000 * 10 ** 6, {'from': customer})

# Create a new policy for a house with a value of 10'000 USDC.
policy = product.applyForPolicy('My house', 10000 * 10 ** 6, {'from': customer})

# Retrieve the `processId` of the new policy
processId = policy.events['LogApplicationCreated'][0]['processId']

# Fetch the state of the applicaton (if [state == 2](https://github.com/etherisc/gif-interface/blob/develop/contracts/modules/IPolicy.sol#L58) -> policy is underwritten)
instanceService.getApplication(processId).dict()

# Fetch the state of the policy (if [state == 0](https://github.com/etherisc/gif-interface/blob/develop/contracts/modules/IPolicy.sol#L59) -> policy is active, also make sure the premiumPaidAmount is > 0 ... if not probably the allowance was not set correctly)
instanceService.getPolicy(processId).dict()
----

=== Sending an oracle response to trigger a claim creation and payout

[source,python]
----
# Retrieve the requestId (created during the underwriting process) of the policy and send oracle response with fire category `M` (20% payout) or use `L` for large fire with 100% payout
requestId = oracle.requestId('My house')
oracle_tx = oracle.respond(requestId, s2h('M'))

# the log list should contain a entry `LogFirePayoutExecuted` with the amount of USDC 2000
oracle_tx.events
----

=== Expiring a policy

[source,python]
----
# this will expire the policy - any claims following after expiration will be rejected due to the policy being expired
product.expirePolicy(processId)
----
