= Setup of the development environment

== Prerequisites

. A running Docker instance (or other compatible container engine) 
. Visual Studio Code (VS Code) with the https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack[Remote Development Extension Pack] installed
. Know how to work with https://code.visualstudio.com/docs/devcontainers/containers[devcontainers]  (optional) 

Installing Docker on Windows is sometimes a struggle.
Recommended Approach: Follow the installation instructions for https://docs.docker.com/desktop/install/windows-install/[Docker Desktop].
Installing Docker on https://docs.docker.com/desktop/install/linux-install/[Linux] or https://docs.docker.com/desktop/install/mac-install/[Mac] should be straight forward.

== Start the sandbox

When you have the container engine up and running, check out the code of the sandbox, open it in VS Code and start the devcontainer (either wait for the pop to build the devcontainer or open the command list (F1) and select the command _Dev Containers: Rebuild and reopen in container_). Once the devcontainer is up and running and has finished compiling the contracts, you can start working with the code.
**Alternatively you can also use Gihub Codespaces to work with the sandbox.**

If you cannot run the vscode devcontainer, then see below in chapter _Run brownie container outside of vscode devcontainer_ for instructions how to run the brownie container manually. When the container is started, continue with the instructions in section xref:firedemo.adoc[Fire insurance demo].

== Run brownie container outside of vscode devcontainer

Build the brownie container 

[source,bash]
----
docker build -t gif-sandbox-brownie -f Dockerfile.brownie-container .
----
Run the brownie container

[source,bash]
----
docker run -v .:/sandbox -p 7545:7545 -p 8000:8000 --name gif-sandbox-brownie gif-sandbox-brownie
----

Start an interactive shell in the brownie container to execute commands

[source,bash]
----
docker exec -it gif-sandbox-brownie bash
----

After that you need to add the ganache network to the brownie config once

[source,bash]
----
brownie networks add Local ganache host=http://localhost:7545 chainid=1337
----


== Reset devcontainer 

To completely reset a devcontainer instance follow these steps

. Shutdown and remove the devcontainer and associated containers
. Remove the `ganache-db` volume from the devcontainers ganache instance
. Delete the file `gif_instance_address.txt` from the project sources
. Restart the devcontainer as described above in the section `Start devcontainer`

