FROM node:lts-bullseye

EXPOSE 7545

RUN npm install -g ganache

CMD ganache-cli \
    --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" \
    --chain.chainId 1234 \
    --port 7545 \
    --accounts 20 \
    #--db .ganache \
    -h "0.0.0.0"
